name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            platform: linux/amd64
          - runs-on: ubuntu-24.04-arm
            platform: linux/arm64
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          PLATFORM: ${{ matrix.platform }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          # Only tag/push "latest" and "${GITHUB_REF_NAME}" (which is version/tag without refs/tags/)
          docker build --platform "$PLATFORM" \
            -t "$REGISTRY/$IMAGE_NAME:latest" \
            -t "$REGISTRY/$IMAGE_NAME:$GITHUB_REF_NAME" .
          docker push --all-tags "$REGISTRY/$IMAGE_NAME"


  create-release:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            README.md
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}